// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-34dgCBhJ-3obl2qrEPWYUQ77QweO228',
    appId: '1:63345703787:web:20333496b050c224b3ea2e',
    messagingSenderId: '63345703787',
    projectId: 'talky-107ac',
    authDomain: 'talky-107ac.firebaseapp.com',
    storageBucket: 'talky-107ac.appspot.com',
    measurementId: 'G-HRDBJZL345',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ8h5lYyuCuI6uzCXHguFPq4gxryDsY0Y',
    appId: '1:63345703787:android:47ca555a326feb41b3ea2e',
    messagingSenderId: '63345703787',
    projectId: 'talky-107ac',
    storageBucket: 'talky-107ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC01lzR8_mR18hjlMQAlex6nWmH_riBT5Q',
    appId: '1:63345703787:ios:fc433a8deff4c894b3ea2e',
    messagingSenderId: '63345703787',
    projectId: 'talky-107ac',
    storageBucket: 'talky-107ac.appspot.com',
    iosClientId: '63345703787-bksv776fd8t0r9afr2ekcnb15j8oumqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.talky',
  );
}
